### ISSUE TITLE
Erm, this.

### ISSUE THREAD

**Issue by amb2127** [CylonicRaider/basebot#4]
basebot.run_minibot(botname='TestBot', nickname='test',
AttributeError: module 'basebot' has no attribute 'run_minibot'

**Comment by CylonicRaider** [comment]
It might be that you have installed the [`basebot` module from PyPI](https://pypi.org/project/basebot/), which is entirely unrelated to this one. If indeed so, remove it and see the [installation guide for *this* `basebot`](https://github.com/CylonicRaider/basebot/blob/master/SETUP.md#installation) for more detailed instructions.

**Comment by amb2127** [comment]
Now it's nonexistent
```
Traceback (most recent call last):
  File "example.py", line 1, in <module>
    import sys, basebot
ModuleNotFoundError: No module named 'basebot'
```

**Comment by CylonicRaider** [comment]
Did you really install the dependency (`pip install -v git+https://github.com/CylonicRaider/websocket-server/`) and the library (`pip install -v git+https://github.com/CylonicRaider/basebot/`)? Have you installed them in the same environment as where you are trying to run the example bot?

**Comment by CylonicRaider** [comment]
Running the two commands in a freshly created Docker container — after installing `pip` and `git` — successfully installed the library for me.

**Comment by amb2127** [comment]
Thanks. You can close this now.

**Comment by CylonicRaider** [comment]
*sees that the issue is already closed and does nothing*
