### ISSUE TITLE
REQUEST: parse sender's account id

### ISSUE THREAD

**Issue by EuphoricCatface** [CylonicRaider/basebot#5]
I would like to utilize it for NowBot registration, so that those with account will be able to automagically register themselves.

**Comment by EuphoricCatface** [comment]
Should have checked pydoc first. Closing.

**Comment by CylonicRaider** [comment]
The account ID is already parsed, and indeed pointed out in the manual; however, the latter should make it clear that the field listing is not complete and that a user ID can be either an `agent:` or an `account:` one.
