### ISSUE TITLE
Code/document mismatch

### ISSUE THREAD

**Issue by EuphoricCatface** [CylonicRaider/basebot#6]
In MANUAL.md, handle_command is stated to take only two arguments
`handle_command(cmdline : list, meta : dict) -> None`

On the other hand, the code expects three arguments
`def handle_command(self, cmdline, meta):`

**Comment by CylonicRaider** [comment]
That is a peculiarity of the Python language rather than my library. In the docs, I present all function signatures from the caller's point of view, thus omitting the implicit `self` argument; self-evidently (pun not intended), it must be present when writing an instance method.

**Comment by CylonicRaider** [comment]
Err... Why has this still been open?
